[project]
name = "com-daily-quote-component"
version = "2.0.0"
description = "A daily quote widget for Class Widgets 2."
authors = [
    {name = "松峰"},
]
readme = "README.md"
requires-python = ">=3.9"
dependencies = ["class-widgets-sdk>=0.6.0"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
